
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 06 03:41:52 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 22;
  public static final int LBRACKET = 43;
  public static final int CHAR = 49;
  public static final int CONST = 5;
  public static final int EQUALS = 24;
  public static final int CASE = 18;
  public static final int LPAREN = 39;
  public static final int GREATER = 29;
  public static final int CONTINUE = 17;
  public static final int LESS = 31;
  public static final int MINUS = 20;
  public static final int RPAREN = 40;
  public static final int CEQUALS = 27;
  public static final int SEMICOLON = 35;
  public static final int AND = 33;
  public static final int GEQUALS = 30;
  public static final int LEQUALS = 32;
  public static final int OR = 34;
  public static final int BOOL = 48;
  public static final int COMMA = 37;
  public static final int CLASS = 4;
  public static final int PLUS = 19;
  public static final int MULTIPLY = 21;
  public static final int IF = 6;
  public static final int DOT = 38;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int RBRACKET = 44;
  public static final int NEW = 11;
  public static final int error = 1;
  public static final int PPLUS = 25;
  public static final int PROGRAM = 2;
  public static final int CNEQUALS = 28;
  public static final int MODULO = 23;
  public static final int NUMBER = 46;
  public static final int IDENT = 47;
  public static final int BREAK = 3;
  public static final int VOID = 15;
  public static final int SWITCH = 8;
  public static final int COLON = 36;
  public static final int LBRACE = 41;
  public static final int ELSE = 7;
  public static final int READ = 13;
  public static final int WHILE = 10;
  public static final int RBRACE = 42;
  public static final int EXTENDS = 16;
  public static final int QUESTION = 45;
  public static final int PRINT = 12;
  public static final int DO = 9;
  public static final int MMINUS = 26;
}

